### ISSUE TITLE
How do you actually use this?

### ISSUE THREAD

**Issue by jdlovins** [pvdstel/scrcpy-vs#1]
I tried compiling it and referencing the DLL but i cant seem to import the name space in another project.

**Comment by jdlovins** [comment]
nevermind had mismatched .net versions. derp

**Comment by jdlovins** [comment]
Actually yeah, how do you use this? An example or something would be great!

**Comment by pvdstel** [comment]
What exactly do you mean, how to use it? It's not really meant as a library, mostly as a little tool to help you control the media on your device if you don't have media keys.

**Comment by pvdstel** [comment]
The idea is that an instance of scrcpy is ran in Visual Studio. What exactly do you need help with?

**Comment by kenliit** [comment]
It's a visual studio extension, not a Winform App.

**Comment by kenliit** [comment]
It's a visual studio extension, not a Winform App.
