### ISSUE TITLE
NuGet Package restore fails for project scrcpy-vs - path is too long...

### ISSUE THREAD

**Issue by elhaix** [pvdstel/scrcpy-vs#6]
This is such a stupid error and wondering why it hasn't been fixed by MS already!

I know the solution is simply to put the solution in a shorter path.  What about creating an alias somewhere and point to that?

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		NuGet Package restore failed for project scrcpy-vs: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.. Please see Error List window for detailed warnings and errors.				

```

**Comment by pvdstel** [comment]
I agree it's a stupid error. Since this issue is not related to the project itself, I'm closing it.
